# Generated by Django 5.2 on 2025-08-31 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pendinguser'),
        ('main_app', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='block',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.college'),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('staff', 'Staff')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
