# Generated by Django 5.2 on 2025-08-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pendinguser_block_pendinguser_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='block',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
