# Generated by Django 5.2 on 2025-08-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_block_profile_course_profile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('staff', 'Staff')], max_length=20, null=True),
        ),
    ]
