# Generated by Django 5.2 on 2025-08-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_class',
        ),
    ]
