# Generated by Django 5.2 on 2025-09-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_user_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='school_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
